password: ENC[AES256_GCM,data:4Vj7jf+mlLBrORCxY+HiQQiedYiJo7Fl0ls1Nmr6tzsiVQNe,iv:Go4j8tXqzo6Hc2GpaG2aYMCHmxYYvUHHs+D5yTfqypo=,tag:KT2kp7Sxgl08c7kz4j9ONg==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAyQWJqRjh6UXpDY3EyMDl3
            bXAzdUdjanhxdnYzdFl1emtHYU1NSmVzd1RjCktKWmRFL1VWa2dTS3BtUVRxZEJL
            andSMXJraC9BQzlpMi8zNG9EaktCR3cKLS0tIEpaSlB5Y0J2QzA5QXVzRmVSaWdq
            aFQyM1BpSVlteGtLdFp4MEozMTh4QXcK/+e521zJcNlelFI2C/Je/vmiQ1k6tbDo
            rP9Rr4GNbXcdj2Vvx7jOFrGBY1A9U1RyFZggNsQ1f224CQwRVMRUnA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age17mpj6p8p8swdgj9etaj60f8aanhztel6ma04g4gex00jr56pp9hsx5gjs9
    lastmodified: "2026-05-21T07:56:22Z"
    mac: ENC[AES256_GCM,data:vIT1eMTBgm71uiH9Anx9eUvKdlus2QrTS/FHMuTslVHslSKT2Fb7DeCItQatrnpU6z79NbMrtb2P0PlGCKxgPSkpOSCKK7Au7JAh+rS42RN9ZHiC2aGfdMfV+hoapM2xWPizZl1LvU2FCKqVI+IJsthKZkr44IDKsxDpQNkls60=,iv:iQqKLdXsqAJ261Q1ussNV6m3BlIv8NqqHnlSsy9iVsc=,tag:+xTroW4+pzCazSamgyyjSA==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.1
