- name: Setup bastion
  hosts: bastion
  roles: [bastion]

- name: Setup servers
  hosts: server
  roles: [server]

- name: Setup k3s on servers
  ansible.builtin.import_playbook: k3s.orchestration.site
